config/routes.rb
Rails.application.routes.draw do
  resources :note_topics
  resources :people
  resources :sizes
  resources :topics
  resources :notes
  
  root "people#index"
  get '/login', to: "sessions#new", as:"login"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  #patch '/topics', to: "topic#delete"
  # delete '/people/delete' to: "people#destroy"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

#<%=sip.map do |obj|%>
  #<%=obj.description%>
  #<%end%>

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
   
    has_many :note_topics
    has_many :topics, through: :note_topics
    # accepts_nested_attributes_for :topics
    def topics_attributes=(topic_attributes)
     topic_attributes.values.each do |topic_attribute|
        topic = Topic.find_or_create_by(topic_attribute)
        self.topics << topic
      end
    end
    belongs_to :size
    
    
    validates :description, :length => {
    :maximum   => 100
    
    
  }
end

app/models/note_topic.rb
class NoteTopic < ApplicationRecord
    belongs_to :note
    belongs_to :topic
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :topics
    has_secure_password
    validates :username, presence: true
    validates :username, uniqueness: true
    validates_length_of :username, maximum: 10, too_many_words: 'Please choose a name with only one word', tokenizer: ->(str) { str.scan(/\w+/) }
     validates_length_of :password, minimum: 6, maximum: 12, too_many_words: 'Please choose a password with only one word', tokenizer: ->(str) { str.scan(/\w+/) }
   # validates :password_digest, numericality: {greater_than_or_equal_to: 6, less_than_or_equal_to: 12}
    

end

app/models/size.rb
class Size < ApplicationRecord
has_many :notes
end

app/models/topic.rb
class Topic < ApplicationRecord
    belongs_to :person
    has_many :note_topics
    has_many :notes, through: :note_topics
    validates :label, presence: true
   # validates :label, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authorized, only: [:login]
    helper_method :current_person, :logged_in?
    def login_user(person)
        session[:person_id] = @person.id
end
#byebug
def current_person
#if session[:person_id]
   # @current_person ||= Person.find(session[:person_id]) if session[:person_id]
if session[:person_id]
    Person.find(session[:person_id])
else
    nil
end
#end
end 

def logged_in?
    !!current_person
end #

def authorized
    unless logged_in?
        flash[:notice] = "you must be logged in to see this page"
        redirect_to login_path
    end 
end 
end

app/controllers/note_topics_controller.rb
class NoteTopicsController < ApplicationController
    before_action :authorized
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authorized
    def show
        @note = Note.find(params[:id])
       #  byebug
      end
      def new
        @note = Note.new 
        #byebug
        @topics = Topic.all.select{|topic| 
        #byebug
        topic.person_id == current_person.id}
      end

      def create
       # byebug
        @note = Note.new(besties)
        if @note.valid?
          @note.save
          #byebug
          redirect_to person_path(session[:person_id])
        else
          flash[:error] = @note.errors.full_messages
          render :new
         #  <%= f.collection_select , Power.all, :id, :name %>
    
        end
      end
      def edit
        @note = Note.find(params[:id])

      end
      def update
        
       @note = Note.find(params[:id])
        @note.update(besties)
        #byebug
        if @note.valid?
         @note.save
          #byebug
          redirect_to person_path(session[:person_id])
        else
          flash[:error] = @note.errors.full_messages
          render :edit
         #  <%= f.collection_select , Power.all, :id, :name %>
    
        end

      end
        private

        def besties
          #byebug
            params.require(:note).permit(:description, :size_id, topic_ids:[])
          end
          #topics_attributes:[:label]
end
#<%= f.fields_for :topics, @note.topics.build do |topics_fields| %>
 # <%= topics_fields.text_field :label %>
#<% end %>

app/controllers/people_controller.rb
class PeopleController < ApplicationController
   #skip_before_action :authorized, only[:new, :create]
   #before_action :authorized
   before_action :authorized
  skip_before_action :authorized, only: [:index, :new, :create]
   
    def show
    
        @person = Person.find(params[:id])
        @topics = Topic.all.select{|topic| topic.person_id == @person.id}
    end 



    def new
        @person = Person.new
    end
    def create
        
        @person = Person.create(params_people)
       # byebug
        if @person.valid?
        
        redirect_to people_path
        else
            render :new
            flash[:error]=@person.errors.full_messages
        end

    end 

    def destroy
        @person = Person.find(session[:person_id])
        @person.destroy
        redirect_to new_person_path
    end

    private

    def params_people
        params.require(:person).permit(:username, :password)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    #before_action :authorized
    #skip_before_action :authorized, only[:new, :create, :login]
    before_action :authorized
  skip_before_action :authorized, only: [:index, :new, :create]
    def new

    end
    def create 
        @person = Person.find_by(username:params[:username])
        #byebug
       
        if @person && @person.authenticate(params[:password])
           # session[:person_id] = @person.id
           login_user(@person)
            redirect_to @person
        else 
            flash[:notice] = 'wrong'
            redirect_to login_path
        end 
        
    end

    def destroy
        session.delete(:person_id)
        flash[:notice] = "logout Succefully"
        redirect_to people_path

    end
end

app/controllers/sizes_controller.rb
class SizesController < ApplicationController
    before_action :authorized
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :authorized
    def show
        @topic = Topic.find(params[:id])
       #  byebug
      end
      def new
        @topic = Topic.new
        #@topics = Topic.all.select{|topic| topic.person_id == current_user.id}.new
      end
      def create
        @topic = Topic.new(besties.merge(person_id: current_person.id))
        if @topic.valid?
          @topic.save
          #byebug
          redirect_to person_path(session[:person_id])
        else
          flash[:errors] = @topic.errors.full_messages
          render :new
         #  <%= f.collection_select , Power.all, :id, :name %>
    
        end
        
        def destroy
          @delete = Delete.find(params[:id])
          @delete.destroy
          redirect_to people_path
        end
      end
        private

        def besties
            params.require(:topic).permit(:label)
          end
          
     
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/note_topics_helper.rb
module NoteTopicsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/edit.html.erb
<h2><%= flash[:error] %></h2>


<h3>Edit Note</h3>
<%= form_for(@note) do |f|%>
    <h2>Description
    <%= f.text_area :description%>
    
    <%= f.submit %>
    </h2>
    <% end %>

app/views/notes/new.html.erb
<h2><%= flash[:error] %></h2>


<h5>Create New Note</h5>
<%= form_for(@note) do |f|%>
    <h2>Description</h2>
    <h2><%= f.text_area :description%></h2>
    <h2>Size Of Text</h2>
    <h2><%= f.collection_select :size_id, Size.all, :id, :size%></h2>
    <h2>Choose Topic To Match Note</h2>
    <h2><%= f.collection_check_boxes :topic_ids, @topics, :id, :label%></h2>
   
    <h3><%= f.submit %></h3>
    <% end %>

app/views/people/index.html.erb
<div class='top-div'>

<h4>Hello Welcome, Login To See Your Notes</h4>

<h2><%=link_to 'login', login_path%></h2>
<h4>New User? Create A User</h4>

<h2><%= link_to 'Sign Up', new_person_path%></h2>


<header class='clearfix'>
 
    <ul>
      <li><%= link_to "Come see all your notes, be happy and smile real big!!!!!!!!", new_person_path %></li>
    </ul>

</header>

</div>

app/views/people/new.html.erb
<h4>Sign up</h4>


    <h3><%= flash[:error] %></h3>
   
<h2>
<%= form_for @person do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %> 
        
  <%= f.label :password %>
  <%= f.text_field :password %>
  
  <%= f.submit %>
  </h2>
<% end %>

app/views/people/show.html.erb
<% if @person.username %>
Username: <%= @person.username %>


    
    <h3>Choose A Topic To See Your Notes/</h3>
    
    <%@topics.each do |object|%>
        
        <h2><li><%=link_to object.label, topic_path(object)%> 
        </li></h2>
       
        
<%end%>

    <h2>Create A New Topic/Create A New Note</h2>
   <h2> <%=link_to 'Create New Topic', new_topic_path%>/<%=link_to 'Create New Note', new_note_path%></h2>
    
    
    <h2></h2>
    <h2></h2>
    
    
    <h1></h1>

<%end%>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<h2>Emergency Only, Delete Account And Data<%= button_to 'DELETE', '/people/:id', method: :delete, data: {confirm: "Are you sure you  want to delete this user?"}%></h2>
    <h2>To Logout Press Here<%= button_to 'Logout', '/logout', method: :delete, data: {confirm: "Are you sure you  want to logout?"}%></h2>

app/views/topics/new.html.erb
<% if !!flash[:errors] %>
<h2><%= flash[:errors] %></h2>
<% end %>

<h3>New Topic </h3>
<h2>
<%= form_for(@topic) do |f| %>
    <%= f.text_field :label %>

    <%= f.submit %>
    </h2>
<%end%>

app/views/topics/show.html.erb
<%  Note.all.map do |object|%>

  <% object.id == 1%>

  <%end%>

  <%@topic.note_ids%>
  <% @topic.note_topics.select do |objects|%>
    <% %>
    <% @specific = Note.all.select do |object| %>
        <%object.id == objects.note_id%>
        <%end%>
        
        <%@specific.select do |hash|%>
          
          <div class="image">
          <li>

          <br>
 
         
         <h<%=hash.size_id%>>
         <br> 
         <br>
        
       <%= hash.description%> &nbsp; &nbsp; <%=link_to "edit", edit_note_path(hash)%> 
            <br> 
        
          <br>
          <br>
            </li>
            </h<%=hash.size_id%>>
        
            </div>

           
            <%end%>




    <%end%>